### ISSUE TITLE
question

### ISSUE THREAD

**Issue by GamaTheDev** [Zentoh/Akatori-Game#1]
So is this a token logger for discord or something...
Because I remember downloading this a few days ago and just yesterday I opened my client and lost my account. 
If it's for educational purposes I should at least get my account back, I have a lot of hard work on there

Didn't mention, it was from https://akatori-games.com. I downloaded the application (obviously I shouldn't have, I thought it might have been safe).

**Comment by Zentoh** [comment]
The site is a template, your attackers certainly had to take this one. 
Make a ticket and you'll get your account back in a few days

**Comment by GamaTheDev** [comment]
Seriously??? Where would I put the ticket??

**Comment by GamaTheDev** [comment]
If I send a ticket to the culprit, I would love to if I can because they can certainly give me my account back.

If I send a ticket to Discord, they will barely do anything to help (I've already tried, still trying).

So what kind of ticket should I make??

**Comment by Zentoh** [comment]
https://support.discord.com/hc/fr/requests/new
